### ISSUE TITLE
adding executable

### ISSUE THREAD

**Issue by tehseensagar** [chinarulezzz/pixload#1]
Hello,

Thanks for such a nice tool, is it possible to add exe payload in shell code? . Also good write with demo with working of this tool.

Regards

**Comment by chinarulezzz** [comment]
What interests you can be found by the query "image x86 polyglot". As an example: https://www.rapid7.com/db/modules/encoder/x86/bmp_polyglot

The `pixload` has no such purpose, afaik. However, Pull Requests are welcome.

> Also good write with demo with working of this tool.

See  #4 for more info.
