### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by wowits** [chinarulezzz/pixload#16]
Hi There, 
How to change the resolution of  the image as some sites  have minimum requirement 1400 * 1400  and the payload image resolution of 32*32 can and if I wanna change the File type.

**Comment by chinarulezzz** [comment]
@wowits 

```sh
$ pixload-png -W 1400 -H 1400 Image.png
```

The other image formats is coming soon.

P.S. The only problem is the polyglot images. See #7 for more information.
